version: "3.9"

services:
  app:
    build: .
    container_name: godmanagerbot
    command: python -u main.py
    volumes:
      - .:/app
    working_dir: /app
    depends_on: []
    environment:
      - PYTHONUNBUFFERED=1
